[package]
name = "kajiya-kay-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
glm = "0.2.3"
image = "0.24.5"
num-traits = "0.2.15"
once_cell = "1.17.1"
winit = "0.28.1"
